---
title: "R Notebook"
output: html_notebook
---
```{r}
library("ggplot2")
library("gganimate")
theme_set(theme_bw())
```

```{r}
p <- 0.2
n_flips <- 100
x <- rbinom(n_flips, 1, p)
x
```

```{r}
a0 <- 1
b0 <- 1
x_grid <- seq(0, 1, 0.01)

params <- list()
density <- list()
for (i in seq_len(n_flips)) {
  params[[i]] <- data.frame(
    "i" = i,
    "a" = a0 + sum(x[1:i]),
    "b" = b0 + i - sum(x[1:i])
  )
  density[[i]] <- data.frame(
    "i" = rep(i, length(x_grid)),
    "x" = x_grid,
    "density" = dbeta(x_grid, params[[i]]$a, params[[i]]$b)
  )
}

#params <- do.call(rbind, params)
density <- do.call(rbind, density)
```

```{r}
ggplot(density) +
  geom_point(aes(x = x, y = density)) +
  transition_time(i)
```

```{r}
observations <- list()
for (i in seq_len(n_flips)) {
  nx <- sum(x[1:i])
  nx_ <- i - sum(x[1:i])
  observations[[i]] <- rbind(
    data.frame(
      i = rep(i, nx),
      x = rep(1, nx),
      nx = seq_len(nx)
    ),
    data.frame(
      i = rep(i, nx_),
      x = rep(0, nx_),
      nx = seq_len(nx_)
    )
  )
}

observations <- do.call(rbind, observations)
observations$x <- as.factor(observations$x)

ggplot(observations) +
  geom_point(aes(x = x, y = nx), col = "black", size = 3) +
  geom_point(aes(x = x, y = nx, col = x), size = 2) +
  scale_color_brewer(palette = "Set2") +
  transition_time(i)
```

